# Generated by Django 3.1.2 on 2020-10-18 02:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('contact_person_name', models.CharField(default='abc', max_length=255, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
                ('source', models.TextField(null=True)),
                ('current_stage', models.TextField(null=True)),
                ('last_follow_up_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Lead',
            },
        ),
        migrations.CreateModel(
            name='Follow_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follo_up_date', models.DateField(default=datetime.date.today)),
                ('response', models.CharField(max_length=500)),
                ('medium', models.CharField(choices=[('Phone Call', 'Phone Call'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email')], max_length=100)),
                ('cont_person_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.lead')),
            ],
            options={
                'verbose_name_plural': 'Follow Up',
            },
        ),
    ]
