# Generated by Django 3.1.2 on 2020-10-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_lead_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_up',
            name='cont_person_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='task.lead'),
        ),
    ]
