# Generated by Django 3.1.2 on 2020-10-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20201018_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow_up',
            new_name='Followup',
        ),
    ]
