# Generated by Django 3.1.2 on 2020-10-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20201018_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='cont_person_name',
            new_name='lead',
        ),
    ]
